login:
    path: /login
    defaults: { _controller: Ibexa\Core\MVC\Symfony\Controller\SecurityController::loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

ibexa_core_internal:
    resource: '@IbexaCoreBundle/Resources/config/routing/internal.yml'
